# Generated by Django 2.2 on 2021-12-26 23:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time ')),
                ('name', models.CharField(max_length=50, verbose_name='city name')),
                ('desc', models.TextField(max_length=200, verbose_name='description')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'City',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time ')),
                ('name', models.CharField(max_length=50, verbose_name='organization name')),
                ('desc', models.TextField(verbose_name='description')),
                ('tag', models.CharField(default='world famous', max_length=10, verbose_name='organization tag')),
                ('category', models.CharField(choices=[('third party org', 'third party'), ('individual', 'individual'), ('college', 'college')], default='organization', max_length=20, verbose_name='org category')),
                ('click_nums', models.IntegerField(default=0, verbose_name='click num')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='favorite num')),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='logo')),
                ('address', models.CharField(default='', max_length=100, verbose_name='address')),
                ('students', models.IntegerField(default=0, verbose_name='student nums')),
                ('course_nums', models.IntegerField(default=0, verbose_name='course nums')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.City', verbose_name='cities')),
            ],
            options={
                'verbose_name': 'Course Organization',
                'verbose_name_plural': 'Course Organization',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time ')),
                ('name', models.CharField(max_length=50, verbose_name='organization name')),
                ('work_years', models.IntegerField(default=0, verbose_name='work years')),
                ('work_company', models.CharField(max_length=50, verbose_name='work company')),
                ('work_position', models.CharField(max_length=50, verbose_name='work position')),
                ('style', models.CharField(max_length=50, verbose_name='teaching style')),
                ('click_nums', models.IntegerField(default=0, verbose_name='click num')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='favorite num')),
                ('age', models.IntegerField(default=18, verbose_name='age')),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='profile picture')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profile',
            },
        ),
    ]
