# Generated by Django 2.2 on 2021-12-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='user_name')),
                ('nickname', models.CharField(default='', max_length=50, verbose_name='nick_name')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('gender', models.CharField(choices=[('male', 'nan'), ('female', 'nv')], max_length=6, verbose_name='gender')),
                ('address', models.CharField(default='', max_length=100, verbose_name='address')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='mobile number')),
                ('image', models.ImageField(default='default.jpg', upload_to='head_image/%Y/%m')),
            ],
            options={
                'verbose_name': 'user_info',
                'verbose_name_plural': 'user_info',
            },
        ),
    ]
