# Generated by Django 2.2 on 2021-12-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinquiry',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='phone number'),
        ),
    ]
